-- 조회수가 가장 높은 중고거래 게시물에 대한 첨부파일 경로 조회 (즉, 중고거래 게시물에 가장 많은 조회수에 관한 경로를 출력)
-- MySQL
SELECT CONCAT('/home/grep/src/', BOARD.BOARD_ID, '/' , FILE.FILE_ID, FILE.FILE_NAME, FILE.FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD BOARD
         JOIN USED_GOODS_FILE FILE ON BOARD.BOARD_ID = FILE.BOARD_ID
WHERE BOARD.VIEWS = (SELECT MAX(B.VIEWS) FROM USED_GOODS_BOARD B)
ORDER BY FILE.FILE_ID DESC;


-- Oracle
SELECT '/home/grep/src' || '/' || F.BOARD_ID || '/' || F.FILE_ID || F.FILE_NAME || F.FILE_EXT FILE_PATH
FROM USED_GOODS_FILE F
         LEFT JOIN USED_GOODS_BOARD B ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(INB.VIEWS) FROM USED_GOODS_BOARD INB)
ORDER BY F.FILE_ID DESC;