-- MySQL
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
         INNER JOIN ANIMAL_INS INS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC
    LIMIT 2;


-- Oracle
SELECT *
FROM (
         SELECT INS.ANIMAL_ID, INS.NAME
         FROM ANIMAL_INS INS
                  INNER JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
         ORDER BY OUTS.DATETIME - INS.DATETIME DESC
     )
WHERE ROWNUM <= 2;