-- MySQL
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
         JOIN ANIMAL_INS INS ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE TIMEDIFF(OUTS.DATETIME, INS.DATETIME) < 0
ORDER BY INS.DATETIME;


-- Oracle
SELECT INS.ANIMAL_ID, INS.NAME
FROM ANIMAL_INS INS
         INNER JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME
ORDER BY INS.DATETIME;