-- mysql
SELECT GU.USER_ID, GU.NICKNAME, CONCAT(GU.CITY, ' ' , GU.STREET_ADDRESS1, ' ', GU.STREET_ADDRESS2) AS 전체주소, CONCAT(SUBSTRING(GU.TLNO, 1, 3), '-', SUBSTRING(GU.TLNO, 4, 4), '-', SUBSTRING(GU.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD GB
         LEFT JOIN USED_GOODS_USER GU ON GB.WRITER_ID = GU.USER_ID
GROUP BY GU.USER_ID
HAVING COUNT(*) >= 3
ORDER BY GU.USER_ID DESC;


-- oracle
SELECT GU.USER_ID, GU.NICKNAME, GU.CITY || ' ' || GU.STREET_ADDRESS1 || ' ' || GU.STREET_ADDRESS2 AS 전체주소, SUBSTR(GU.TLNO, 1, 3) || '-' || SUBSTR(GU.TLNO, 4, 4) || '-' || SUBSTR(GU.TLNO, 8, 4) AS 전화번호
FROM USED_GOODS_USER GU
         LEFT JOIN USED_GOODS_BOARD GB ON GU.USER_ID = GB.WRITER_ID
GROUP BY GU.USER_ID, GU.NICKNAME, GU.CITY, GU.STREET_ADDRESS1, GU.STREET_ADDRESS2, GU.TLNO
HAVING COUNT(*) >= 3
ORDER BY GU.USER_ID DESC;